name: CI/CD — Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build et Push de l'image Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build de l'image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-php:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-php:${{ github.run_number }} .

      - name: Push de l'image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/projet-php:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/projet-php:${{ github.run_number }}